name: L10n Focus iOS screenshots (one set of locales only)
on:
  workflow_call:
    inputs:
      locales:
        required: true
        type: string

jobs:
    get-screenshots:
        name: Generate screenshots
        runs-on: macos-15
        steps:
            - name: Clone firefox-ios repo
              uses: actions/checkout@v4
              with:
                repository: mozilla-mobile/firefox-ios
            - name: Setup Xcode
              run: |
                  sudo rm -rf /Applications/Xcode.app
                  sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
                  xcodebuild -version
            - name: Run setup scripts for Focus
              run: |
                  ./checkout.sh
            - name: Compile Focus iOS
              run: |
                  xcodebuild build-for-testing -scheme FocusSnapshotTests \
                    -project focus-ios/Blockzilla.xcodeproj \
                    -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.2' \
                    -derivedDataPath l10n-screenshots-dd
            - name: Generate screenshots
              continue-on-error: true
              run: |
                  focus-ios/l10n-screenshots.sh --test-without-building ${{ env.get_locales.group1 }}
            - name: Upload screenshots
              uses: actions/upload-artifact@v4.3.3
              with:
                path: ./l10n-screenshots
                retention-days: 90
                name: Screenshots