name: Firefox & Focus iOS build metrics
on:
  workflow_dispatch:
    inputs:
      runner:
        description: "Github Actions runner"
        default: "macos-14"
        required: true
        type: string
      xcode:
        description: "Xcode version"
        default: "15.3"
        required: true
        type: string
      ios_simulator:
        description: "iPhone/iPad simulator"
        default: "iPhone 15"
        required: true
        type: string
      ios_version:
        description: "iOS version"
        default: "17.4"
        required: true
        type: string

jobs:
  Print-Environment:
    name: Environment (Xcode ${{ inputs.xcode }}, ${{ inputs.ios_simulator }}, iOS ${{ inputs.ios_version }})
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Print all input variables and env info
        run: |
          echo "Runner:\t\t${{ inputs.runner }}"
          echo "Xcode:\t\t${{ inputs.xcode }}"
          echo "Device:\t\t${{ inputs.ios_simulator }}"
          echo "iOS:\t\t${{ inputs.ios_version }}"
          sw_vers
          uname -av
  Firefox:
    needs: Print-Environment
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Clone firefox-ios repo
        uses: actions/checkout@v4
        with:
          repository: mozilla-mobile/firefox-ios
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.11'
      - name: Install Python packages required
        run: |
          brew update
          pip3 install virtualenv pipenv
      - name: Setup Xcode
        run: |
          sudo rm -rf /Applications/Xcode.app
          sudo xcode-select -s /Applications/Xcode_${{ inputs.xcode }}.app/Contents/Developer
          xcodebuild -version
      - name: Run setup scripts for Firefox
        run: |
          sh ./bootstrap.sh --force
      - name: Resolve dependencies
        run: |
          rm -fr ~/Library/Developer/Xcode/DerivedData/Client-*
          xcodebuild -resolvePackageDependencies -onlyUsePackageVersionsFromResolvedFile
        working-directory: firefox-ios
      - name: Build Firefox
        run: 
          time xcodebuild build-for-testing -project Client.xcodeproj -scheme Fennec -configuration Fennec -sdk iphonesimulator -destination 'platform=iOS Simulator,name=${{ inputs.ios_simulator }},OS=${{ inputs.ios_version }}'
        working-directory: firefox-ios
      - name: Size of source and app files
        run: |
          du -sh .
          du -sh ~/Library/Developer/Xcode/DerivedData/Client-*/Build/Products/Fennec-iphonesimulator/Client.app
        working-directory: firefox-ios
      - name: Run Firefox unit tests
        run: |
          time xcodebuild test-without-building -target Client -scheme Fennec -destination 'platform=iOS Simulator,name=${{ inputs.ios_simulator }},OS=${{ inputs.ios_version }}'
        working-directory: firefox-ios
        continue-on-error: true
      - name: Run Firefox smoke tests
        run: |
          # time xcodebuild test-without-building -target Client -scheme Fennec -destination 'platform=iOS Simulator,name=${{ inputs.ios_simulator }},OS=${{ inputs.ios_version }}' -testPlan Smoketest1
          time xcodebuild test-without-building -target Client -scheme Fennec -destination 'platform=iOS Simulator,name=${{ inputs.ios_simulator }},OS=${{ inputs.ios_version }}' -testPlan Smoketest2
          # time xcodebuild test-without-building -target Client -scheme Fennec -destination 'platform=iOS Simulator,name=${{ inputs.ios_simulator }},OS=${{ inputs.ios_version }}' -testPlan Smoketest3
          # time xcodebuild test-without-building -target Client -scheme Fennec -destination 'platform=iOS Simulator,name=${{ inputs.ios_simulator }},OS=${{ inputs.ios_version }}' -testPlan Smoketest4 
        working-directory: firefox-ios
        continue-on-error: true
  Focus:
    needs: Print-Environment
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Clone firefox-ios repo
        uses: actions/checkout@v4
        with:
          repository: mozilla-mobile/firefox-ios
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Python packages required
        run: |
          brew update
          pip3 install virtualenv pipenv
      - name: Setup Xcode
        run: |
          sudo rm -rf /Applications/Xcode.app
          sudo xcode-select -s /Applications/Xcode_${{ inputs.xcode }}.app/Contents/Developer
          xcodebuild -version
      - name: Run setup scripts for Focus
        run: |
          sh ./checkout.sh
      - name: Resolve dependencies (Focus)
        run: |
          rm -fr ~/Library/Developer/Xcode/DerivedData/Blockzilla-* 
          xcodebuild -resolvePackageDependencies -onlyUsePackageVersionsFromResolvedFile
        working-directory: focus-ios
      - name: Build Focus
        run: time xcodebuild build-for-testing -scheme Focus -target XCUITest -configuration FocusDebug -destination 'platform=iOS Simulator,name=${{ inputs.ios_simulator }},OS=${{ inputs.ios_version }}'
        working-directory: focus-ios
      - name: Size of source and app files
        run: |
          du -sh .
          du -sh ~/Library/Developer/Xcode/DerivedData/Blockzilla-*/Build/Products/FocusDebug-iphonesimulator/Firefox\ Focus.app
        working-directory: focus-ios
      - name: Run Focus unit tests
        run: |
          time xcodebuild test -scheme Focus -target XCUITest -configuration FocusDebug -destination 'platform=iOS Simulator,name=${{ inputs.ios_simulator }},OS=${{ inputs.ios_version }}' -testPlan UnitTests
        working-directory: focus-ios
        continue-on-error: true
      - name: Run Focus smoke tests
        run: |
          time xcodebuild test -scheme Focus -target XCUITest -configuration FocusDebug -destination 'platform=iOS Simulator,name=${{ inputs.ios_simulator }},OS=${{ inputs.ios_version }}' -testPlan SmokeTest
        working-directory: focus-ios
        continue-on-error: true