name: Firefox & Focus iOS build metrics
on:
  workflow_dispatch:
    inputs:
      runner:
        description: "Github Actions runner"
        default: "macos-14"
        required: true
        type: string
      xcode:
        description: "Xcode version"
        default: "15.2"
        required: true
        type: string
      ios_simulator:
        description: "iPhone/iPad simulator"
        default: "iPhone 15"
        required: true
        type: string
      ios_version:
        description: "iOS version"
        default: "17.2"
        required: true
        type: string

jobs:
  Firefox-Focus:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Clone firefox-ios repo
        uses: actions/checkout@v4
        with:
          repository: mozilla-mobile/firefox-ios
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.11'
      - name: Install Python packages required
        run: |
          brew update
          pip3 install virtualenv pipenv
      - name: Run setup scripts for Firefox and Focus
        run: |
          sh ./bootstrap.sh --force
          sh ./checkout.sh
      - name: Setup Xcode
        run: |
          sudo rm -rf /Applications/Xcode.app
          sudo xcode-select -s /Applications/Xcode_${{ inputs.xcode }}.app/Contents/Developer
          xcodebuild -version
      - name: Resolve dependencies (Firefox)
        run: |
          rm -fr ~/Library/Developer/Xcode/DerivedData/Client-*
          xcodebuild -resolvePackageDependencies -onlyUsePackageVersionsFromResolvedFile
        working-directory: firefox-ios
      - name: Build Firefox
        run: 
          time xcodebuild build-for-testing -project Client.xcodeproj -scheme Fennec -configuration Fennec -sdk iphonesimulator -destination 'platform=iOS Simulator,name=${{ inputs.ios_simulator }},OS=${{ inputs.ios_version }}'
        working-directory: firefox-ios
      - name: Size of source and app file (Firefox)
        run: |
          du -sh .
          du -sh ~/Library/Developer/Xcode/DerivedData/Client-*/Build/Products/Fennec-iphonesimulator/Client.app
        working-directory: firefox-ios
      - name: Resolve dependencies (Focus)
        run: |
          rm -fr ~/Library/Developer/Xcode/DerivedData/Blockzilla-* 
          xcodebuild -resolvePackageDependencies -onlyUsePackageVersionsFromResolvedFile
        working-directory: focus-ios
      - name: Build Focus
        run: time xcodebuild build-for-testing -scheme Focus -target XCUITest -configuration FocusDebug -destination 'platform=iOS Simulator,name=${{ inputs.ios_simulator }},OS=${{ inputs.ios_version }}'
        working-directory: focus-ios
      - name: Size of source and app file (Focus)
        run: |
          du -sh .
          du -sh ~/Library/Developer/Xcode/DerivedData/Blockzilla-*/Build/Products/FocusDebug-iphonesimulator/Firefox\ Focus.app
        working-directory: focus-ios