name: Firefox iOS repo size
on:
  workflow_dispatch:
    inputs:
        runner:
          description: "Github Actions runner"
          default: "macos-14"
          required: true
          type: string
        xcode:
          description: "Xcode version"
          default: "15.4"
          required: true
          type: string
        ios_simulator:
          description: "iPhone/iPad simulator"
          default: "iPhone 15"
          required: true
          type: string
        ios_version:
          description: "iOS version"
          default: "17.4"
          required: true
          type: string
        branch:
          description: "Branch, tag or SHA"
          default: "main"
          required: true
          type: string

jobs:
  report-size:
    name: Generate Report
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Clone firefox-ios repo
        uses: actions/checkout@v4
        with:
          repository: mozilla-mobile/firefox-ios
          ref: ${{ inputs.branch }}
      - name: Test Print report
        run: | 
          current_sha=`git rev-parse HEAD`
          echo "Branch/tag/SHA: ${{ inputs.branch }}" >> $GITHUB_STEP_SUMMARY
          if [ ${{ inputs.branch }} == "main" ];
          then
            echo "$current_sha" >> $GITHUB_STEP_SUMMARY
          fi
      - name: Query source code size
        id: query_source_code
        run: |
          source_code_size=`du -sh . | awk '{ print $1 }'`
          echo "Source code size: $source_code_size"
          echo "source_code_size=$source_code_size" >> $GITHUB_OUTPUT
      - name: Setup Xcode
        run: |
          sudo rm -rf /Applications/Xcode.app
          sudo xcode-select -s /Applications/Xcode_${{ inputs.xcode }}.app/Contents/Developer
          xcodebuild -version
      - name: Run setup scripts for Firefox
        run: |
          sh ./bootstrap.sh --force
      - name: Compile source code
        id: compile
        run: |
          xcodebuild \
            build-for-testing \
            -target Client \
            -scheme Fennec \
            -derivedDataPath ~/DerivedData \
            -destination 'platform=iOS Simulator,name=${{ inputs.ios_simulator }},OS=${{ inputs.ios_version }}' \
            COMPILER_INDEX_STORE_ENABLE=NO CODE_SIGN_IDENTITY= CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO ARCH="arm64"
        working-directory: firefox-ios
      - name: Query derived data size
        id: query_derived_data
        run: |
          derived_data_size=`du -sh ~/DerivedData | awk '{ print $1 }'`
          echo "Derived data size: $derived_data_size"
          echo "derived_data_size=$derived_data_size" >> "$GITHUB_OUTPUT"
      - name: Query app size
        id: query_app
        run: |
          app_size=`du -sh ~/DerivedData/Build/Products/Fennec-iphonesimulator/Client.app | awk '{ print $1 }'`
          echo "App size: $app_size"
          echo "app_size=$app_size"  >> "$GITHUB_OUTPUT"
      - name: Print report
        run: | 
          current_sha=`git rev-parse HEAD`
          echo "Branch/tag/SHA: ${{ inputs.branch }}" >> $GITHUB_STEP_SUMMARY
          if [ ${{ inputs.branch }} == "main" ];
          then
            echo "$current_sha" >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Source code size: ${{ steps.query_source_code.outputs.source_code_size }}" >> $GITHUB_STEP_SUMMARY
          echo "Derived data size: ${{ steps.query_derived_data.outputs.derived_data_size}}" >> $GITHUB_STEP_SUMMARY
          echo "App size: ${{ steps.query_app.outputs.app_size }}" >> $GITHUB_STEP_SUMMARY