name: L10n Focus iOS screenshots
on:
  workflow_dispatch:
    inputs:
      branch:
        default: main
        required: true
        type: string

jobs:
    get_locales:
        name: Get locales
        runs-on: macos-15
        steps:
            - name: Clone firefoxios-l01n repo
              uses: actions/checkout@v4
              with:
                repository: mozilla-l10n/firefoxios-l10n
            - name: Determine locales needed
              id: locales
              run: |
                ls | grep -e "^..$" -e "^..-..$" > locales.txt
                split -n 3 locales.txt locales-
                group1=`tr '\n' ',' < locales-aa`
                group2=`tr '\n' ',' < locales-ab`
                group3=`tr '\n' ',' < locales-ac`
                echo "group1=$group1" >> $GITHUB_ENV
                echo "group2=$group2" >> $GITHUB_ENV
                echo "group3=$group3" >> $GITHUB_ENV
    dispatch_locales_1:
        name: Dispatch locales 1
        needs: get_locales
        runs-on: macos-15
        steps:
            - name: Clone this repo
              uses: actions/checkout@v4
              with:
                repository: clarmso/firefox-ios-tools-experiment
            - name: Do something?
              run: |
                ls .github/workflows/
                pwd
            - name: Dispatch group1 to L10n screenshots
              uses: ./.github/workflows
              with:
                locales: ${{ env.get_locales.locales.group1 }}
    dispatch_locales_2:
        name: Dispatch locales 2
        needs: get_locales
        runs-on: macos-15
        steps:
            - name: Clone this repo
              uses: actions/checkout@v4
              with:
                repository: clarmso/firefox-ios-tools-experiment
            - name: Do something?
              run: |
                ls .github/workflows/
                pwd
            - name: Dispatch group2 to L10n screenshots
              uses: ./.github/workflows/
              with:
                locales: ${{ env.get_locales_locales.group2 }}
    dispatch_locales_3:
        name: Dispatch locales 3
        needs: get_locales
        runs-on: macos-15
        steps:
            - name: Clone this repo
              uses: actions/checkout@v4
              with:
                repository: clarmso/firefox-ios-tools-experiment
            - name: Do something?
              run: |
                ls .github/workflows/
                pwd
            - name: Dispatch group3 to L10n screenshots
              uses: ./.github/workflows
              with:
                locales: ${{ env.get_locales.locales.group3 }}
              
