name: L10n Focus iOS screenshots
on:
  workflow_dispatch:

jobs:
    generate-screenshots:
      strategy:
        matrix: 
          group: [ "1", "2", "3" ]
      uses: ./.github/workflows/L10n-focus-locales.yml
      with:
        locale_group: "${{ matrix.group }}"