name: L10n Focus iOS screenshots
on:
  workflow_dispatch:

jobs:
  determine-locales:
    name: Determine lists of locales
    runs-on: macos-15
    outputs:
      groups: ${{ steps.confirm.outputs.groups }}
    steps:
      - name: Clone firefoxios-l01n repo
        uses: actions/checkout@v4
        with:
          repository: mozilla-l10n/firefoxios-l10n
      - name: Determine locales needed
        id: my_locales
        run: |
          ls | grep -e "^..$" -e "^..-..$" > locales.txt
          split -n 3 locales.txt locales-
          group1=`tr '\n' ' ' < locales-aa`
          group2=`tr '\n' ' ' < locales-ab`
          group3=`tr '\n' ' ' < locales-ac`
          echo "locales=$group1" >> $GITHUB_ENV
          echo "locales=$group2" >> $GITHUB_ENV
          echo "locales=$group3" >> $GITHUB_ENV
      - name: Confirm list of locales
        id: confirm
        run: |
          echo "groups=[\"$group1\",\"$group2\",\"$groups3\"]" >> $GITHUB_OUTPUT

  generate-screenshots:
    name: Generate Screenshots
    needs: determine-locales
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        locales: [ "${{ needs.determine-locales.outputs.groups }}" ]
    uses: ./.github/workflows/L10n-focus-locales.yml
    with:
      locales: "${{ matrix.locales }}"