name: L10n Focus iOS screenshots
on:
  workflow_dispatch:
    inputs:
      branch:
        default: main
        required: true
        type: string

jobs:
    get_locales:
        name: Get locales
        runs-on: macos-15
        steps:
            - name: Clone firefoxios-l01n repo
              uses: actions/checkout@v4
              with:
                repository: mozilla-l10n/firefoxios-l10n
            - name: Determine locales needed
              id: locales
              run: |
                ls | grep -e "^..$" -e "^..-..$" > locales.txt
                split -n 3 locales.txt locales-
                group1=`tr '\n' ',' < locales-aa`
                group2=`tr '\n' ',' < locales-ab`
                group3=`tr '\n' ',' < locales-ac`
                echo "group1=$group1" >> $GITHUB_ENV
                echo "group2=$group2" >> $GITHUB_ENV
                echo "group3=$group3" >> $GITHUB_ENV
    call-reusable:
      needs: get_locales
      uses: ./.github/workflows/reusable.yml
      with:
        username: "${{ github.action.job.get_locales.group1 }}"