name: L10n screenshots
on:
  workflow_dispatch:
    inputs:
      branch:
        default: main
        required: true
        type: string

jobs:
    get-screenshots:
        name: Generate screenshots
        runs-on: macos-15
        steps:
            - name: Clone firefox-ios repo
              uses: actions/checkout@v4
              with:
                repository: mozilla-mobile/firefox-ios
                ref: ${{ inputs.branch }}
            - name: Setup Xcode
              run: |
                  sudo rm -rf /Applications/Xcode.app
                  sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
                  xcodebuild -version
            - name: Run setup scripts for Firefox
              run: |
                  sh ./bootstrap.sh --force
            - name: Compile Firefox iOS
              run: |
                  xcodebuild build-for-testing -project firefox-ios/Client.xcodeproj -scheme L10nSnapshotTests \
                    -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.2' \
                    -testPlan L10nSnapshotTests \
                    -derivedDataPath l10n-screenshots-dd
            - name: Generate screenshots
              continue-on-error: true
              run: |
                  firefox-ios/l10n-screenshots.sh --test-without-building en-CA fr
            - name: Upload screenshots
              uses: actions/upload-artifact@v4.3.3
              with:
                path: ./l10n-screenshots
                retention-days: 90
                name: Screenshots