name: L10n Focus iOS screenshots
on:
  workflow_dispatch:

jobs:
  determine-locales:
    name: Determine lists of locales
    runs-on: macos-15
    outputs:
      group1: ${{ steps.my_locales.outputs.group1 }}
      group2: ${{ steps.my_locales.outputs.group2 }}
      group3: ${{ steps.my_locales.outputs.group3 }}
    steps:
      - name: Clone firefoxios-l01n repo
        uses: actions/checkout@v4
        with:
          repository: mozilla-l10n/firefoxios-l10n
      - name: Determine locales needed
        id: my_locales
        run: |
          ls | grep -e "^..$" -e "^..-..$" > locales.txt
          split -n 3 locales.txt locales-
          group1=`tr '\n' ' ' < locales-aa`
          group2=`tr '\n' ' ' < locales-ab`
          group3=`tr '\n' ' ' < locales-ac`
          echo "group1=$group1" >> $GITHUB_OUTPUT
          echo "group2=$group2" >> $GITHUB_OUTPUT
          echo "group3=$group3" >> $GITHUB_OUTPUT
  
  generate-screenshots:
    name: Generate Screenshots
    needs: determine-locales
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        locales: [ 
          "${{ needs.determine-locales.outputs.group1 }}", 
          "${{ needs.determine-locales.outputs.group2 }}",
          "${{ needs.determine-locales.outputs.group3 }}"]  
    uses: ./.github/workflows/L10n-focus-locales.yml
    with:
      locales: "${{ matrix.locales }}"