name: L10n Focus iOS screenshots (one set of locales only)
on:
  workflow_call:
    inputs:
      locale_group:
        required: true
        type: string
      branch:
        required: false
        type: string
        default: "main"

jobs:
    get-screenshots:
        name: Generate screenshots
        runs-on: macos-15
        steps:
            - name: Clone firefoxios-l01n repo
              uses: actions/checkout@v4
              with:
                repository: mozilla-l10n/firefoxios-l10n
            - name: Determine locales needed
              id: my_locales
              run: |
                ls | grep -e "^..$" -e "^..-..$" > locales.txt
                split -n 3 locales.txt locales-
                group1=`tr '\n' ' ' < locales-aa`
                group2=`tr '\n' ' ' < locales-ab`
                group3=`tr '\n' ' ' < locales-ac`
                if [[ "${{ inputs.locale_group }}" == "1" ]]; then
                  echo $group1
                  echo "locales=$group1" >> $GITHUB_ENV
                elif [[ "${{ inputs.locale_group }}" == "2" ]]; then
                  echo $group2
                  echo "locales=$group2" >> $GITHUB_ENV
                elif [[ "${{ inputs.locale_group }}" == "3" ]]; then
                  echo $group3
                  echo "locales=$group3" >> $GITHUB_ENV
                fi
                cat $GITHUB_ENV
                rm -fr firefoxios-l10n/
            - name: Clone firefox-ios repo
              uses: actions/checkout@v4
              with:
                repository: mozilla-mobile/firefox-ios
                ref: ${{ inputs.branch }}
            - name: Setup Xcode
              run: |
                  sudo rm -rf /Applications/Xcode.app
                  sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
                  xcodebuild -version
            - name: Run setup scripts for Focus
              run: |
                  ./checkout.sh
            - name: Compile Focus iOS
              run: |
                  xcodebuild build-for-testing -scheme FocusSnapshotTests \
                    -project focus-ios/Blockzilla.xcodeproj \
                    -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.2' \
                    -derivedDataPath l10n-screenshots-dd
            - name: Generate screenshots
              continue-on-error: true
              run: |
                  focus-ios/l10n-screenshots.sh --test-without-building ${{ env.locales }}
            - name: Upload screenshots
              uses: actions/upload-artifact@v4.3.3
              with:
                path: ./l10n-screenshots
                retention-days: 90
                name: Screenshots