name: Reusable Workflow
on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs and Secrets
        run: |
          echo "Hello, ${{ inputs.username }}"
