name: Test Network Connection

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  test-network:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-15, ubuntu-latest]

    steps:
      - name: Test network connection
        run: |
          echo "Testing network connection on ${{ matrix.os }}..."

          # Check if curl can reach a specific URL
          echo "Testing HTTP connection with curl..."
          urls=(
            "https://www.google.com"
            "https://www.mozilla.org/en-US/firefox/products"
            "https://www.mozilla.org/en-US/book/"
            "https://www.wikipedia.org"
            "https://www.youtube.com"
            "https://www.example.com"
            "https://www.google.com/search?q=ps5&source=hp&ei=yDybY7_iBMSH9u8P-fWwkAs&iflsig=AJiK0e8AAAAAY5tK2K2eVYMzMJI3G8qcqgmnGdrC6UVp&ved=0ahUKEwi_5s_h9_v7AhXEg_0HHfk6DLIQ4dUDCAg&uact=5&oq=ps5&gs_lcp=Cgdnd3Mtd2l6EAMyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIICAAQgAQQyQMyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEOgsILhCABBDHARDRAzoFCC4QgAQ6CAguEIAEENQCUIoEWOwGYKIJaAFwAHgAgAFLiAHcAZIBATOYAQCgAQGwAQA&sclient=gws-wiz"
            )
          for url in "${urls[@]}"; do
            echo "Testing $url..."
            curl -I $url
          done

          echo "Network connection test completed."