name: Test Network Connection

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  test-network:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-15, ubuntu-latest]

    steps:
      - name: Test network connection
        run: |
          echo "Testing network connection on ${{ matrix.os }}..."

          # Check if curl can reach a specific URL
          echo "Testing HTTP connection with curl..."
          urls=(
            "https://www.google.com", 
            "https://www.mozilla.org/en-US/firefox/products",
            "https://www.mozilla.org/en-US/book/",
            "https://www.wikipedia.org",
            "https://www.youtube.com"
            )
          for url in "${urls[@]}"; do
            echo "Testing $url..."
            curl -I "$url"
          done

          echo "Network connection test completed."